export const ROUTES = {
  home: '/',
  catalog: '/catalog',
  product: '/products/:productId',
  masters: '/masters',
  master: '/masters/:masterId',
  shelves: '/shelves',
  giftQuiz: '/gift-quiz',
  rentShelf: '/rent-shelf',
  events: '/events',
  favorites: '/favorites',
  adminLogin: '/admin-login',
  adminDashboard: '/admin',
  adminProducts: '/admin/products',
  adminMasters: '/admin/masters',
  adminShelves: '/admin/shelves',
  adminApplications: '/admin/applications',
  adminBookings: '/admin/bookings',
  adminEvents: '/admin/events',
} as const
